# Generated by Django 3.1.3 on 2020-11-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits_count', models.PositiveIntegerField(default=0, verbose_name='Count Visits')),
                ('http_user_agent', models.CharField(max_length=255, verbose_name='http user agent')),
                ('remote_addr', models.CharField(max_length=255, verbose_name='remote addr')),
                ('last_visit', models.DateTimeField(verbose_name='last visit')),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
            ],
        ),
    ]
